//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVatTuPhanXuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPhuKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPhuKien()
        {
            this.tThanhPhans = new HashSet<tThanhPhan>();
        }
    
        public string MaPhuKien { get; set; }
        public string TenPhuKien { get; set; }
        public string MaNuoc { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuongTonThucTe { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tNuocSX tNuocSX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tThanhPhan> tThanhPhans { get; set; }
    }
}
