//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVatTuPhanXuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tThanhPhan
    {
        public string MaXe { get; set; }
        public string MaPhuKien { get; set; }
        public string DVT { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual tPhuKien tPhuKien { get; set; }
        public virtual tXe tXe { get; set; }
    }
}
